name: 'Deploy to AWS S3'
description: 'Deploy a file to AWS S3'
inputs:
  bucket:
    description: 'The name of the bucket to deploy to'
    required: true
  bucket-region:
    description: 'The region of the bucket to deploy to'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'